// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: glimr.proto

package glimr

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GlimrClient is the client API for Glimr service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GlimrClient interface {
	RequestVote(ctx context.Context, in *RequestVoteRequest, opts ...grpc.CallOption) (*RequestVoteResponse, error)
}

type glimrClient struct {
	cc grpc.ClientConnInterface
}

func NewGlimrClient(cc grpc.ClientConnInterface) GlimrClient {
	return &glimrClient{cc}
}

func (c *glimrClient) RequestVote(ctx context.Context, in *RequestVoteRequest, opts ...grpc.CallOption) (*RequestVoteResponse, error) {
	out := new(RequestVoteResponse)
	err := c.cc.Invoke(ctx, "/glimr.Glimr/RequestVote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GlimrServer is the server API for Glimr service.
// All implementations must embed UnimplementedGlimrServer
// for forward compatibility
type GlimrServer interface {
	RequestVote(context.Context, *RequestVoteRequest) (*RequestVoteResponse, error)
	mustEmbedUnimplementedGlimrServer()
}

// UnimplementedGlimrServer must be embedded to have forward compatible implementations.
type UnimplementedGlimrServer struct {
}

func (UnimplementedGlimrServer) RequestVote(context.Context, *RequestVoteRequest) (*RequestVoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestVote not implemented")
}
func (UnimplementedGlimrServer) mustEmbedUnimplementedGlimrServer() {}

// UnsafeGlimrServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GlimrServer will
// result in compilation errors.
type UnsafeGlimrServer interface {
	mustEmbedUnimplementedGlimrServer()
}

func RegisterGlimrServer(s grpc.ServiceRegistrar, srv GlimrServer) {
	s.RegisterService(&Glimr_ServiceDesc, srv)
}

func _Glimr_RequestVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestVoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GlimrServer).RequestVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/glimr.Glimr/RequestVote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GlimrServer).RequestVote(ctx, req.(*RequestVoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Glimr_ServiceDesc is the grpc.ServiceDesc for Glimr service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Glimr_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "glimr.Glimr",
	HandlerType: (*GlimrServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestVote",
			Handler:    _Glimr_RequestVote_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "glimr.proto",
}
